# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/Website" # Location of package manifests
    schedule:
      interval: "weekly"
    groups:
      website-core:
        patterns:
          - "*next*"
          - "nextra*"
          - "react*"
          - "@react*"
          - "swr*"
          - "react-icons*"
          - "tailwindcss*"
          - "@tailwindcss/*"
          - "postcss*"
          - "eslint*"
          - "@eslint*"
          - "@types/node*"
          - "@types/react*"
          - "@types/react-dom*"
          - "typescript*"
          - "dompurify*"
      tooling-misc:
        patterns:
          - "pagefind*"
          - "standard*"
          - "@vercel/*"
          - "@theguild/*"
    commit-message:
      prefix: "chore(npm)"
    labels:
      - "dependencies 📦️"
      - "npm 📦️"

  - package-ecosystem: "maven"
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    groups:
      openrewrite-dependencies:
        patterns:
          - "org.openrewrite*"
      javafx-dependencies:
        patterns:
          - "org.openjfx*"
    commit-message:
      prefix: "chore(maven)"
    labels:
      - "dependencies 📦️"
      - "maven 📦️"

  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "weekly"
    groups:
      docker-gh-actions-dependencies:
        patterns:
          - "docker*"
    commit-message:
      prefix: "chore(ci)"
    labels:
      - "dependencies 📦️"
      - "CI/CD 🔁"

  - package-ecosystem: "docker"
    directories:
      - "/Docker/dev/CLI"
      - "/Docker/dev/GUI"
      - "/Docker/dev/commons/base"
      - "/Docker/dev/commons/runner"
      - "/Docker/prod/CLI"
      - "/Docker/prod/GUI"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(docker)"
    labels:
      - "dependencies 📦️"
      - "docker 🐋"
