package preferences;

import java.util.prefs.Preferences;

public interface Labels {
    Preferences PREFERENCES = Preferences.userNodeForPackage(Labels.class);
    String LAST_YT_DLP_UPDATE_TIME = "LAST_YT_DLP_UPDATE_TIME";
    String LAST_FOLDER = "LAST_FOLDER";
    String YT_DLP_VERSION = "YT_DLP_VERSION";
    String YT_DLP_UPDATING = "YT_DLP_UPDATING";
    String SPOTIFY_ACCESS_TOKEN = "SPOTIFY_ACCESS_TOKEN";
    String IS_FFMPEG_WORKING = "IS_FFMPEG_WORKING";
    String FFMPEG_VERSION = "FFMPEG_VERSION";
    String NEW_DRIFTY_VERSION_NAME = "NEW_DRIFTY_VERSION_NAME";
    String LATEST_DRIFTY_VERSION_TAG = "LATEST_DRIFTY_VERSION_TAG";
    String LAST_DRIFTY_UPDATE_TIME = "LAST_DRIFTY_UPDATE_TIME";
    String EARLY_ACCESS = "EARLY_ACCESS";
    String DRIFTY_UPDATE_AVAILABLE = "DRIFTY_UPDATE_AVAILABLE";
    String FOLDERS = "FOLDERS";
    String GUI_AUTO_PASTE = "GUI_AUTO_PASTE";
    String GUI_THEME = "GUI_THEME";
}
