name: 📄 Documentation Change request
description: Change regarding improving the docs to be more accessible
title: "[DOCS] "
labels: ["documentation 📝"]
body:
  - type: textarea
    attributes:
      label: Category of documentation update
      description: |
        What category does this change fall under? For example, Typo, New category addition, Rephrasing the sentences, fixing broken links, etc.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe the change you think might work
      description: Please describe the change & need of the change in utmost detail possible.
    validations:
      required: true
  - type: textarea
    id: extrainfo
    attributes:
      label: Additional information
      description: Add any other context about the change in the documentation here.
    validations:
      required: false
  - type: dropdown
    id: assignee
    attributes:
      label: Do you want to work on this issue?
      multiple: false
      options:
        - "Yes"
        - "No"
      default: 0
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        You can also join our [Discord community](https://discord.gg/DeT4jXPfkG) for any help or support.