name: 💡 Feature Request
description: Suggest a new feature for Drifty
title: "[FEATURE] "
labels: [enhancement]
body:
  - type: textarea
    id: related-problem-for-feature-request
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: A clear and concise description of what the problem is.
      placeholder: I'm always frustrated when [...]
    validations:
      required: false
  - type: textarea
    id: feature-description
    attributes:
      label: Describe the solution you'd like.
      description: A clear and concise description of what feature you want to include.
    validations:
      required: true
  - type: dropdown
    id: app-ver
    attributes:
      label: Application Version
      description: Please select the application version (Check it here - https://github.com/SaptarshiSarkar12/Drifty/releases/)
      options:
        - v1.2.0
        - v1.1.0
        - v1.0.0
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Please add relevant screenshots for the feature.
    validations:
      required: false
  - type: textarea
    id: extrainfo
    attributes:
      label: Additional information
      description: Add any other context about the feature here.
    validations:
      required: false
