name: Other
description: Want to raise a different issue?
title: "[OTHER] "
labels: [Other issue]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A detailed description of the issue with links and screenshots.
    validations:
      required: true
  - type: dropdown
    id: app-ver
    attributes:
      label: Application Version
      description: Please select the application version (Check it here - https://github.com/SaptarshiSarkar12/Drifty/releases/)
      options:
        - v1.2.2
        - v1.2.1
        - v1.2.0
        - v1.1.0
        - v1.0.0
    validations:
      required: true
  - type: textarea
    id: extrainfo
    attributes:
      label: Additional information
      description: Add any other context about the issue here.
    validations:
      required: false
