name: Upgrade npm packages
defaults:
    run:
        working-directory: "./Website"
on:
   workflow_dispatch:
   
   schedule:
   - cron: "0 0 * * *"

jobs:
   upgrade-packages:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout the repository
          uses: actions/checkout@v3
          
        - name: Setup Node.js
          uses: actions/setup-node@v3
          with:
            node-version: '16'
            cache: 'npm'
        
        - name: Upgrade Packages
          run: |
             npm install -g npm-check-updates
             ncu -u
             npm install
             
        - name: Commit and push changes to the repository
          run: |
              git config user.name "GitHub Actions Bot"
              git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
               git commit -m "build(App): Built And Packaged Drifty for Windows"
              git commit -m "build(App): Built And Packaged Drifty for Windows"
              git push
