name: Test Java Code

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  test:
    name: Run Tests
    strategy:
        matrix:
            os: ["windows-latest", "macos-latest", "ubuntu-latest"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: 21
      - name: Install ffmpeg
        shell: bash
        run: |
          if [ ${{ matrix.os }} == 'ubuntu-latest' ]; then
             cd Core/src/main/resources
             chmod +x spotdl_linux
             ./spotdl_linux --download-ffmpeg
          elif [ ${{ matrix.os }} == 'macos-latest' ]; then
             cd Core/src/main/resources
             chmod +x spotdl_macos
             ./spotdl_macos --download-ffmpeg
          elif [ ${{ matrix.os }} == 'windows-latest' ]; then
             cd Core/src/main/resources
             chmod +x spotdl_windows.exe
             ./spotdl_win.exe --download-ffmpeg
          fi
      - name: Run Tests
        run: mvn test
